id: I969185C1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T07:12:37+00:00'
last_modified: '2022-06-07T21:57:05.251973+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD95814
  title: དུས་འཁོར་མཆན་འགྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    76A2:
      image_group_id: I1PD95824
      title: ''
      total_pages: 372
      order: 1
      base_file: 76A2.txt
    A197:
      image_group_id: I1PD95825
      title: ''
      total_pages: 512
      order: 2
      base_file: A197.txt
    00EB:
      image_group_id: I1PD95826
      title: ''
      total_pages: 502
      order: 3
      base_file: 00EB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
